-- Railway Directory: security hardening migration
-- Run this in Supabase SQL Editor AFTER confirming your existing tables/columns.
-- This script is intentionally fail-closed for writes.

begin;

-- ================================================================
-- 1. Role table
-- ================================================================
create table if not exists public.user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('admin', 'editor', 'viewer')),
  created_at timestamptz not null default now()
);

alter table public.user_roles enable row level security;

-- A user may see only their own role. There are deliberately NO client
-- INSERT/UPDATE/DELETE policies. Role assignment is performed by a trusted
-- administrator through the Supabase dashboard or a server-side process.
drop policy if exists "Users can read their own role" on public.user_roles;
create policy "Users can read their own role"
on public.user_roles
for select
to authenticated
using (user_id = auth.uid());

-- ================================================================
-- 2. RLS on directory tables
-- ================================================================
alter table public.sections enable row level security;
alter table public.stations enable row level security;

-- Remove the old overly-broad policies from the previous application.
drop policy if exists "Public read access" on public.sections;
drop policy if exists "Public read access" on public.stations;
drop policy if exists "Authenticated write access" on public.sections;
drop policy if exists "Authenticated update access" on public.sections;
drop policy if exists "Authenticated delete access" on public.sections;
drop policy if exists "Authenticated write access" on public.stations;
drop policy if exists "Authenticated update access" on public.stations;
drop policy if exists "Authenticated delete access" on public.stations;

-- Public directory data remains readable. If the directory must be internal,
-- replace these two policies with TO authenticated policies instead.
create policy "Public directory read - sections"
on public.sections
for select
to anon, authenticated
using (true);

create policy "Public directory read - stations"
on public.stations
for select
to anon, authenticated
using (true);

-- Only editor/admin can insert or update. Only admin can delete.
create policy "Editors and admins can insert sections"
on public.sections
for insert
to authenticated
with check (
  exists (
    select 1 from public.user_roles r
    where r.user_id = auth.uid()
      and r.role in ('admin', 'editor')
  )
);

create policy "Editors and admins can update sections"
on public.sections
for update
to authenticated
using (
  exists (
    select 1 from public.user_roles r
    where r.user_id = auth.uid()
      and r.role in ('admin', 'editor')
  )
)
with check (
  exists (
    select 1 from public.user_roles r
    where r.user_id = auth.uid()
      and r.role in ('admin', 'editor')
  )
);

create policy "Only admins can delete sections"
on public.sections
for delete
to authenticated
using (
  exists (
    select 1 from public.user_roles r
    where r.user_id = auth.uid()
      and r.role = 'admin'
  )
);

create policy "Editors and admins can insert stations"
on public.stations
for insert
to authenticated
with check (
  exists (
    select 1 from public.user_roles r
    where r.user_id = auth.uid()
      and r.role in ('admin', 'editor')
  )
);

create policy "Editors and admins can update stations"
on public.stations
for update
to authenticated
using (
  exists (
    select 1 from public.user_roles r
    where r.user_id = auth.uid()
      and r.role in ('admin', 'editor')
  )
)
with check (
  exists (
    select 1 from public.user_roles r
    where r.user_id = auth.uid()
      and r.role in ('admin', 'editor')
  )
);

create policy "Only admins can delete stations"
on public.stations
for delete
to authenticated
using (
  exists (
    select 1 from public.user_roles r
    where r.user_id = auth.uid()
      and r.role = 'admin'
  )
);

-- ================================================================
-- 3. Audit log
-- ================================================================
create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  action text not null,
  table_name text not null,
  record_id text,
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

alter table public.audit_log enable row level security;

drop policy if exists "Admins can read audit log" on public.audit_log;
create policy "Admins can read audit log"
on public.audit_log
for select
to authenticated
using (
  exists (
    select 1 from public.user_roles r
    where r.user_id = auth.uid()
      and r.role = 'admin'
  )
);

-- No client INSERT policy: audit entries are created only by trusted triggers.

create or replace function public.write_audit_log()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.audit_log (
    user_id, action, table_name, record_id, old_data, new_data
  ) values (
    auth.uid(),
    tg_op,
    tg_table_name,
    coalesce((to_jsonb(new)->>'id'), (to_jsonb(old)->>'id')),
    case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) else null end
  );
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

-- Avoid duplicate triggers if this migration is run more than once.
drop trigger if exists audit_sections on public.sections;
drop trigger if exists audit_stations on public.stations;

create trigger audit_sections
after insert or update or delete on public.sections
for each row execute function public.write_audit_log();

create trigger audit_stations
after insert or update or delete on public.stations
for each row execute function public.write_audit_log();

-- ================================================================
-- 4. Recommended integrity indexes/constraints
-- ================================================================
create index if not exists idx_stations_section_order
  on public.stations(section_id, display_order);

create index if not exists idx_audit_log_created_at
  on public.audit_log(created_at desc);

commit;

-- ================================================================
-- 5. Assign your first administrator
-- ================================================================
-- After creating the user in Supabase Authentication > Users, run:
--
-- insert into public.user_roles (user_id, role)
-- select id, 'admin'
-- from auth.users
-- where email = 'YOUR-ADMIN-EMAIL@example.com'
-- on conflict (user_id) do update set role = excluded.role;
--
-- IMPORTANT: Do not create a public INSERT policy on user_roles.
